# Generated by Django 5.0.7 on 2024-08-05 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_route_distance_city_unique_city_for_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='rows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seats_in_row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
